// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20260313032206_Added unique index in the log")]
    partial class Addeduniqueindexinthelog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitGracePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HabitStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitId", "LogDate")
                        .IsUnique();

                    b.ToTable("HabitLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
