// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HabitTracker.Migrations
{
    [DbContext(typeof(HabitContext))]
    [Migration("20260322165509_AddedHabitGroup")]
    partial class AddedHabitGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HabitGracePeriod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HabitGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HabitStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HabitGroupId");

                    b.ToTable("Habits");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitGroup", b =>
                {
                    b.Property<int>("HabitGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("HabitGroupId");

                    b.ToTable("HabitGroups");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitLog", b =>
                {
                    b.Property<Guid>("HabitLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("TEXT");

                    b.HasKey("HabitLogId");

                    b.HasIndex("HabitId", "LogDate")
                        .IsUnique();

                    b.ToTable("HabitLogs");
                });

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.HasOne("HabitTracker.Models.HabitGroup", "HabitGroup")
                        .WithMany("Habits")
                        .HasForeignKey("HabitGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitGroup");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitLog", b =>
                {
                    b.HasOne("HabitTracker.Models.Habit", "Habit")
                        .WithMany("HabitLogs")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");
                });

            modelBuilder.Entity("HabitTracker.Models.Habit", b =>
                {
                    b.Navigation("HabitLogs");
                });

            modelBuilder.Entity("HabitTracker.Models.HabitGroup", b =>
                {
                    b.Navigation("Habits");
                });
#pragma warning restore 612, 618
        }
    }
}
